"""make username unique

Revision ID: 3045d7831258
Revises: eb868f92aa10
Create Date: 2023-08-28 15:58:43.423998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3045d7831258'
down_revision = 'eb868f92aa10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
