"""expand book model

Revision ID: 4545c3a5fd78
Revises: 4ca110dbb4fe
Create Date: 2023-08-28 09:56:08.429454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4545c3a5fd78'
down_revision = '4ca110dbb4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('edition', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('format', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('num_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('genre_list', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('genre_list')
        batch_op.drop_column('genres')
        batch_op.drop_column('rating')
        batch_op.drop_column('num_pages')
        batch_op.drop_column('format')
        batch_op.drop_column('edition')
        batch_op.drop_column('description')
        batch_op.drop_column('authors')

    # ### end Alembic commands ###
