"""set up relationship for user and cart

Revision ID: 46adf0c161be
Revises: 6d98768cbb7f
Create Date: 2023-08-28 11:22:48.492555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46adf0c161be'
down_revision = '6d98768cbb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_carts',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_carts_book_id_books')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_book_carts_cart_id_carts')),
    sa.PrimaryKeyConstraint('book_id', 'cart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_carts')
    # ### end Alembic commands ###
