"""removed genre-list

Revision ID: eb868f92aa10
Revises: f999874221f6
Create Date: 2023-08-28 14:53:14.446314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb868f92aa10'
down_revision = 'f999874221f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('genre_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_list', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
