"""<descriptive message>

Revision ID: f93056c0fe61
Revises: 3045d7831258
Create Date: 2023-08-30 11:03:43.659364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93056c0fe61'
down_revision = '3045d7831258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.drop_constraint('uq_users_username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
