"""changed cart to cartitem

Revision ID: f999874221f6
Revises: 46adf0c161be
Create Date: 2023-08-28 11:34:24.321456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f999874221f6'
down_revision = '46adf0c161be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_cart_items_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cart_items_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book_carts')
    op.drop_table('carts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_carts_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_carts',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_book_carts_book_id_books'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='fk_book_carts_cart_id_carts'),
    sa.PrimaryKeyConstraint('book_id', 'cart_id')
    )
    op.drop_table('cart_items')
    # ### end Alembic commands ###
